# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt install build-essential cmake curl libmpfr-dev libmpc-dev libgmp-dev e2fsprogs ninja-build qemu-system-gui qemu-system-x86 qemu-utils ccache rsync unzip texinfo
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt install gcc-11 g++-11
          git clone https://github.com/SerenityOS/serenity
          cd serenity
          Meta/serenity.sh rebuild-toolchain
          Meta/serenity.sh build
          Meta/serenity.sh install
          Meta/serenity.sh image
          cd Ports
          sed -i "s/exit 1/exit 0/g" build_all.sh
          ./build_all.sh
          cd ..
          Meta/serenity.sh build
          Meta/serenity.sh install
          Meta/serenity.sh image
          cd Build/i686
          ninja grub-image
          curl -T grub_disk_image temp.sh
